### ISSUE TITLE
Flutter icon material | Flutter

### ISSUE THREAD

**Issue by AhmadApriliyanto23** [AhmadApriliyanto23/Berandaku#39]
[https://api.flutter.dev/flutter/material/Icons-class.html](url)

![image](https://github.com/user-attachments/assets/00da4dd5-1596-46c2-9e2d-60669d7625ea)
![image](https://github.com/user-attachments/assets/a520cc05-fd24-4167-adf8-6ef94dae05e4)
![image](https://github.com/user-attachments/assets/c64fcadc-dfed-4ab3-b1a1-82345930f9fb)

**Comment by Radheshg04** [comment]
Please explain the issue in detail. I'd like to work on this

**Comment by AhmadApriliyanto23** [comment]
Sorry brother, this is a documentation section that I made personally and if you find it and think this is an issue, actually this is not an issue.
